[tool.poetry]
name = "vectors"
version = "1.0.0"
description = ""
authors = ["qzonic <lazzytoo@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.4"
matplotlib = "^3.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
